// Public export surface for agora-convo-ai-toolkit
export { AgoraVoiceAI, AgoraVoiceAI as ConversationalAIAPI } from './core/conversational-ai';
export {
  type AgoraVoiceAIConfig,
  type AgoraVoiceAIConfig as IConversationalAIAPIConfig,
  type RTCEngine,
  type RTMEngine,
  type RTCStreamMessagePublisher,
} from './core/config';
export { CovSubRenderController } from './rendering/sub-render';
export { ChunkedMessageAssembler } from './messaging/chunked';
export {
  type IMetricsReporter,
  ConsoleMetricsReporter,
  AgoraMetricsReporter,
} from './utils/metrics';

// --- Consumer-facing types from core/types ---
export {
  // Enums
  AgentState,
  AgentState as EAgentState,
  TurnStatus,
  TurnStatus as ETurnStatus,
  TranscriptHelperMode,
  TranscriptHelperMode as ETranscriptHelperMode,
  MessageSalStatus,
  MessageSalStatus as EMessageSalStatus,
  ModuleType,
  ModuleType as EModuleType,
  ChatMessageType,
  ChatMessageType as EChatMessageType,
  ChatMessagePriority,
  ChatMessagePriority as EChatMessagePriority,
  ThinkListeningAction,
  ThinkListeningAction as EThinkListeningAction,
  ThinkThinkingAction,
  ThinkThinkingAction as EThinkThinkingAction,
  ThinkSpeakingAction,
  ThinkSpeakingAction as EThinkSpeakingAction,
  MessageType,
  MessageType as EMessageType,
  LocalTranscriptStatus,
  LocalTranscriptStatus as ELocalTranscriptStatus,
  RTMEventType,
  RTMEventType as ERTMEvents,
  RTCEventType,
  RTCEventType as ERTCEvents,
  RTCCustomEventType,
  RTCCustomEventType as ERTCCustomEvents,
  // Error classes
  ConversationalAIError,
  NotInitializedError,
  RTMRequiredError,
  NotFoundError,
  // Type aliases & interfaces
  type AgoraVoiceAIState,
  type AgentMetric,
  type AgentMetric as TAgentMetric,
  type ModuleError,
  type ModuleError as TModuleError,
  type StateChangeEvent,
  type StateChangeEvent as TStateChangeEvent,
  type SegmentedLatency,
  type Turn,
  type Turn as TAgentTurnFinished,
  type MessageReceipt,
  type MessageReceipt as TMessageReceipt,
  type ChatMessageText,
  type ChatMessageText as IChatMessageText,
  type ChatMessageImage,
  type ChatMessageImage as IChatMessageImage,
  type ChatMessageBase,
  type ChatMessageBase as IChatMessageBase,
  type SpeakMessage,
  type SpeakMessage as ISpeakMessage,
  type ThinkMessage,
  type ThinkMessage as IThinkMessage,
  type UserTranscription,
  type UserTranscription as IUserTranscription,
  type AgentTranscription,
  type AgentTranscription as IAgentTranscription,
  type TranscriptionBase,
  type TranscriptionBase as ITranscriptionBase,
  type MessageInterrupt,
  type MessageInterrupt as IMessageInterrupt,
  type MessageError,
  type MessageError as IMessageError,
  type MessageMetrics,
  type MessageMetrics as IMessageMetrics,
  type TurnFinishedMessage,
  type TurnFinishedMessage as ITurnFinishedMessage,
  type MessageSalStatusData,
  type MessageSalStatusData as IMessageSalStatus,
  type UserManualEventPayload,
  type UserManualSosEvent,
  type UserManualEosEvent,
  type AgentManualEosPayload,
  type AgentManualEosEvent,
  type TranscriptHelperItem,
  type TranscriptHelperItem as ITranscriptHelperItem,
  type TranscriptHelperObjectWord,
  type TranscriptHelperObjectWord as TTranscriptHelperObjectWord,
  type DataChunkMessageWord,
  type DataChunkMessageWord as TDataChunkMessageWord,
  type LocalTranscriptionBase,
  type LocalTranscriptionBase as ILocalTranscriptionBase,
  type LocalImageTranscription,
  type LocalImageTranscription as ILocalImageTranscription,
  type UserTracks,
  type UserTracks as IUserTracks,
  type PresenceState,
  type PresenceState as IPresenceState,
  type QueueItem,
  type QueueItem as TQueueItem,
  type HelperRTCEvents,
  type HelperRTCEvents as IHelperRTCEvents,
} from './core/types';

// --- Consumer-facing types from core/events ---
export {
  AgoraVoiceAIEvents,
  AgoraVoiceAIEvents as EConversationalAIAPIEvents,
  EventLogLevel,
  type AgoraVoiceAIEventHandlers,
  type AgoraVoiceAIEventHandlers as IConversationalAIAPIEventHandlers,
} from './core/events';
